language: node_js

node_js:
  - '11.10.1'

sudo: required

services:
  - docker

sudo: required

cache:
  directories:
  - node_modules

before_script:
  - echo "REACT_APP_RAPID_API_KEY=${REACT_APP_RAPID_API_KEY}" > .env
  - npm install -g firebase-tools
  - npm install

script:
  - npm test
  - npm run build
  - docker build -t jabaridash/realestate .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push jabaridash/realestate

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN" --non-interactive --only hosting
  on:
    branch: master
